# Create your compose file. To learn more, please visit
# https://docs.docker.com/reference/compose-file/
services:
  local-nim:
    image: nvcr.io/nim/meta/llama-3.1-8b-instruct:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ~/.cache/nim
        target: /opt/nim/.cache/
    environment:
      - NIM_MODEL_PROFILE=193649a2eb95e821309d6023a2cabb31489d3b690a9973c7ab5d1ff58b0aa7eb
      - NGC_API_KEY=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
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge